# Site settings
title: Ziyang's blog
email: liuziyang1106@buaa.edu.cn
description: "Vision and Insight"
baseurl: ""
url: "http://liuziyang1106.github.io"
github_username:  liuziyang1106

cdn:
    jsdelivr:
        enabled: true

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
mathjax: true
